# Generated by Django 4.0.3 on 2022-03-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='day', max_length=15)),
                ('hour', models.CharField(choices=[('10', '10'), ('18', '18')], default='hour', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FilmDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany')], default='country', max_length=3)),
                ('premiere', models.DateField()),
                ('director', models.CharField(default='director', max_length=32)),
                ('title', models.CharField(default='title', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FilmMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='film.filmdate')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='film.filmdetail')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.filmmain')),
            ],
        ),
    ]
